spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all routes
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true # Set to true only if credentials are required
      routes:
        - id: authentication-service
          uri: lb:http://authentication-service
          predicates:
            - Method=GET,POST,PUT,DELETE,OPTIONS
            - Path=/authentication/**

        - id: address-service
          uri: lb:http://address-service
          predicates:
            - Method=GET,POST,PUT,DELETE,OPTIONS
            - Path=/address/**

        - id: freelancer-service
          uri: lb:http://freelancer-service
          predicates:
            - Method=GET,POST,PUT,DELETE,OPTIONS
            - Path=/freelancer/**

server:
  port: 8090
