spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: authentication-service
  mail:
    host: localhost
    port: 1025
    username: ismailkattan.contact@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    default-encoding: UTF-8
gorevce:
  app:
    jwtSecret: SaK_SaU_BBF_CS_GoReVcE_SecretKey_2024_2025_bilgisayar_muhendisligi_tasarimi_54_halep_iskenderiye
    jwtExpirationMs: 86400000


